### ISSUE TITLE
Default env var in dockerfile and document necessary env vars

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_controller#1]
Atm necessary env (UID, GID, UMASK) variables are only documented in the make file. 
Necessary variables should be documented in readme too.

Besides this, in my opinion the image should be able to be started without env with the default values of the dockerfile.

**Comment by bertsky** [comment]
> Atm necessary env (UID, GID, UMASK) variables are only documented in the make file.
> Necessary variables should be documented in readme too.

They are not really _necessary_ (in the sense that you have to customize or even know about them), and they are documented in the makefile's self-documentation (`make help`), but I'll add a section to the README, agreed.

> Besides this, in my opinion the image should be able to be started without env with the default values of the dockerfile.

That's not possible though. The Dockerfile does not know about your runtime user context. Whoever has control over /data and /models should also be the controlling user.

Also, what's so bad about environment variables in Docker?
