### ISSUE TITLE
Naming convention: Change ssh user name to ocrd-controller or something similar

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_controller#2]
On the cli it is difficult to see if you are directly in manager or controller. Suggest to postfix default ssh names.

![image](https://user-images.githubusercontent.com/3832618/156013890-66bc19bb-6fb2-46e6-b0cf-1f0240beef36.png)

**Comment by bertsky** [comment]
That seems like a pretty bad reason for changing the user name.

If all you want is to better see which server you are on in the interactive context, consider giving your services networks human-readable names in docker-compose.yml. (Perhaps some further steps are necessary for the login prompt to show them, like setting `HOSTNAME` envvar or adding to `/etc/hosts`...)
